[package]
name = "sift"
version = "0.1.0"
edition = "2024"

[dependencies]
show-image = { version = "0.14.1", features = ["image"] }
image = "0.24"
imageproc = "0.23"
ndarray = "0.15"
egui = "0.22"
eframe = "0.22"
approx = "0.5"
rayon = "1.7"